{
 "title": "River King",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "Клубы", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Количество клубов",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unique_clubs{job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Действия в клубах",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(club_create_total{job=~\"$job\"}[15s])",
     "legendFormat": "Create"
    },
    {
     "expr": "rate(club_delete_total{job=~\"$job\"}[15s])",
     "legendFormat": "Delete"
    },
    {
     "expr": "rate(club_promote_total{job=~\"$job\"}[15s])",
     "legendFormat": "Promote"
    },
    {
     "expr": "rate(club_demote_total{job=~\"$job\"}[15s])",
     "legendFormat": "Demote"
    },
    {
     "expr": "rate(club_join_total{job=~\"$job\"}[15s])",
     "legendFormat": "Join"
    },
    {
     "expr": "rate(club_kick_total{job=~\"$job\"}[15s])",
     "legendFormat": "Kick"
    }
   ]
  },
  { "title": "Уникальные игроки", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Уникальные игроки",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unique_users{job=~\"$job\",period=\"day\"}",
     "legendFormat": "{{period}}"
    },
    {
     "expr": "unique_users{job=~\"$job\",period=\"week\"}",
     "legendFormat": "{{period}}"
    },
    {
     "expr": "unique_users{job=~\"$job\",period=\"month\"}",
     "legendFormat": "{{period}}"
    },
    {
     "expr": "unique_users{job=~\"$job\",period=\"total\"}",
     "legendFormat": "{{period}}"
    }
   ]
  },
  {
   "title": "Уникальные игроки",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unique_users{job=~\"$job\",period=\"day\"} - (unique_users{job=~\"$job\",period=\"day\"} offset 1d)",
     "legendFormat": "{{period}}"
    },
    {
     "expr": "unique_users{job=~\"$job\",period=\"week\"} - (unique_users{job=~\"$job\",period=\"week\"} offset 7d)",
     "legendFormat": "{{period}}"
    },
    {
     "expr": "unique_users{job=~\"$job\",period=\"month\"} - (unique_users{job=~\"$job\",period=\"month\"} offset 30d)",
     "legendFormat": "{{period}}"
    }
   ]
  },
  {
   "title": "Новые регистрации по источникам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (source) (clamp_min(increase(user_registrations{job=~\"$job\",period=\"total\"}[$__rate_interval]), 0))",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Регистрации по источникам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (source) (user_registrations{job=~\"$job\",period=\"total\"})",
     "legendFormat": "{{source}}"
    },
    {
     "expr": "sum by (source) (user_registrations{job=~\"$job\",period=\"day\"})",
     "legendFormat": "{{source}} (24ч)"
    }
   ]
  },
  { "title": "Api вызовы", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Покупки за звезды",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "irate(shop_purchase_click_total{job=~\"$job\"}[1m])",
     "legendFormat": "{{pack}}-purchase"
    },
    {
     "expr": "irate(shop_purchase_denied_total{job=~\"$job\"}[1m])",
     "legendFormat": "{{pack}}-denied"
    },
    {
     "expr": "irate(shop_purchase_failed_total{job=~\"$job\"}[1m])",
     "legendFormat": "{{pack}}-failed"
    },
    {
     "expr": "irate(shop_purchase_complete_total{job=~\"$job\"}[1m])",
     "legendFormat": "{{pack}}-complete"
    }
   ]
  },
  {
   "title": "Покупки за монеты",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "irate(coin_shop_purchase_click_total{job=~\"$job\"}[1m])",
     "legendFormat": "{{pack}}-purchase"
    },
    {
     "expr": "irate(coin_shop_purchase_failed_total{job=~\"$job\"}[1m])",
     "legendFormat": "{{pack}}-failed"
    },
    {
     "expr": "irate(coin_shop_purchase_complete_total{job=~\"$job\"}[1m])",
     "legendFormat": "{{pack}}-complete"
    }
   ]
  },
  {
   "title": "Шеринг картинок и квесты",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "irate(catch_share_total{job=~\"$job\"}[1m])",
     "legendFormat": "catch_share"
    },
    {
     "expr": "irate(quests_complete_total{job=~\"$job\"}[1m])",
     "legendFormat": "quest_completed-{{period}}"
    },
    {
     "expr": "irate(quests_view_total{job=~\"$job\"}[1m])",
     "legendFormat": "quests_viewed"
    }
   ]
  },
  {
   "title": "Вызовы  API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "irate(api_call_total{job=~\"$job\", path=~\"/api/referrals.*|/api/location.*|/api/lure.*|.*/api/tournaments.*\"}[1m])",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "irate(api_call_total{job=~\"$job\", path=\"/api/language\"}[1m])",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "irate(api_call_total{job=~\"$job\", path=\"/api/daily\"}[1m])",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "irate(api_call_total{job=~\"$job\", path=\"/bot\"}[1m])",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "irate(api_call_total{job=~\"$job\", path=\"/api/shop\"}[1m])",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "irate(api_call_total{job=~\"$job\", path=\"/api/guide\"}[1m])",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "irate(api_call_total{job=~\"$job\", path=\"/api/me\"}[1m])",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "sum(irate(api_call_total{job=~\"$job\", path=~\"/api/prizes.*\"}[1m]))",
     "legendFormat": "/api/prizes/{prize}"
    },
    {
     "expr": "sum(irate(api_call_total{job=~\"$job\", path=~\"/api/rod/.*\"}[1m]))",
     "legendFormat": "/api/rod/{rod}"
    },
    {
     "expr": "irate(api_call_total{job=~\"$job\", path=~\"/api/shop\"}[1m])",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "sum(irate(api_call_total{job=~\"$job\", path=~\"/api/ratings/.*\"}[1m]))",
     "legendFormat": "/api/ratings{rating}"
    },
    {
     "expr": "sum(irate(api_call_total{job=~\"$job\", path=\"/api/achievements\"}[1m]))",
     "legendFormat": "/api/achievements"
    },
    {
     "expr": "sum(irate(api_call_total{job=~\"$job\", path=~\"/api/achievements/.*/claim\"}[1m]))",
     "legendFormat": "/api/achievements/{achievement}/claim"
    }
   ]
  },
  {
   "title": "Поймано/упущено",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "irate(cast_total{job=~\"$job\", caught=\"true\"}[1m])",
     "legendFormat": "{{caught}}"
    },
    {
     "expr": "(\r\n  sum by (caught) (\r\n    clamp_min(irate(cast_total{job=~\"$job\", caught=\"false\"}[1m]), 0)\r\n  )\r\n  + on (caught)\r\n  label_set(\r\n    sum(\r\n      clamp_min(irate(hook_total{job=~\"$job\", result=\"escaped\"}[1m]), 0)\r\n    ),\r\n    \"caught\",\"false\"\r\n  )\r\n)\r\nor\r\nsum by (caught) (\r\n  clamp_min(irate(cast_total{job=~\"$job\", caught=\"false\"}[1m]), 0)\r\n)\r\nor\r\nlabel_set(\r\n  sum(\r\n    clamp_min(irate(hook_total{job=~\"$job\", result=\"escaped\"}[1m]), 0)\r\n  ),\r\n  \"caught\",\"false\"\r\n)\r\n",
     "legendFormat": "{{caught}}"
    }
   ]
  },
  {
   "title": "Пойманные рыбы",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "sum by (fish) (irate(fish_caught_total{job=~\"$job\"}[1m]))",
     "legendFormat": "{{fish}}"
    }
   ]
  },
  { "title": "Команды бота", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Попытки купить предметы",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "sum by (pack) (irate(bot_command_total{job=~\"$job\", command=\"buy\"}[1m]))",
     "legendFormat": "stars-{{pack}}"
    },
    {
     "expr": "sum by (pack) (irate(bot_command_total{job=~\"$job\", command=\"coin_buy\"}[1m]))",
     "legendFormat": "coins-{{pack}}"
    }
   ]
  },
  {
   "title": "Все команды",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "sum by (command) (irate(bot_command_total{job=~\"$job\"}[1m]))",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Поймано/упущено",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sum by (result) (irate(bot_command_total{job=~\"$job\", command=\"cast\"}[1m]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Пойманные рыбы",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "sum by (fish) (irate(bot_command_total{job=~\"$job\",command=\"cast\",result=\"caught\"}[1m]))",
     "legendFormat": "{{fish}}"
    }
   ]
  },
  { "title": "Рыбы", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Самые крупные рыбы за неделю",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "max by (fish) (\r\n    max_over_time(catch_weight_kg{job=~\"$job\"}[7d])\r\n  )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Самые мелкие рыбы за неделю",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "min by (fish) (\r\n    min_over_time(catch_weight_kg{job=~\"$job\"}[7d])\r\n  )",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Локации", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "Пруд",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum by (fish) (\r\n    increase( fish_caught_total{job=~\"$job\", location=\"Пруд\"}[7d] )\r\n  )\r\n  + on (fish)\r\n  sum by (fish) (\r\n    increase( bot_command_total{job=~\"$job\", command=\"cast\", result=\"caught\", location=\"1\"}[7d] )\r\n  )\r\n)\r\nor sum by (fish) ( increase(fish_caught_total{job=~\"$job\", location=\"Пруд\"}[7d]) )\r\nor sum by (fish) ( increase(bot_command_total{job=~\"$job\", command=\"cast\", result=\"caught\", location=\"1\"}[7d]) )\r\n",
     "legendFormat": "{{fish}}"
    }
   ]
  },
  {
   "title": "Болото",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum by (fish) (\r\n    increase( fish_caught_total{job=~\"$job\", location=\"Болото\"}[7d] )\r\n  )\r\n  + on (fish)\r\n  sum by (fish) (\r\n    increase( bot_command_total{job=~\"$job\", command=\"cast\", result=\"caught\", location=\"4\"}[7d] )\r\n  )\r\n)\r\nor sum by (fish) ( increase(fish_caught_total{job=~\"$job\", location=\"Болото\"}[7d]) )\r\nor sum by (fish) ( increase(bot_command_total{job=~\"$job\", command=\"cast\", result=\"caught\", location=\"4\"}[7d]) )\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Река",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum by (fish) (\r\n    increase( fish_caught_total{job=~\"$job\", location=\"Река\"}[7d] )\r\n  )\r\n  + on (fish)\r\n  sum by (fish) (\r\n    increase( bot_command_total{job=~\"$job\", command=\"cast\", result=\"caught\", location=\"2\"}[7d] )\r\n  )\r\n)\r\nor sum by (fish) ( increase(fish_caught_total{job=~\"$job\", location=\"Река\"}[7d]) )\r\nor sum by (fish) ( increase(bot_command_total{job=~\"$job\", command=\"cast\", result=\"caught\", location=\"2\"}[7d]) )\r\n",
     "legendFormat": "{{fish}}"
    }
   ]
  },
  {
   "title": "Озеро",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum by (fish) (\r\n    increase( fish_caught_total{job=~\"$job\", location=\"Озеро\"}[7d] )\r\n  )\r\n  + on (fish)\r\n  sum by (fish) (\r\n    increase( bot_command_total{job=~\"$job\", command=\"cast\", result=\"caught\", location=\"3\"}[7d] )\r\n  )\r\n)\r\nor sum by (fish) ( increase(fish_caught_total{job=~\"$job\", location=\"Озеро\"}[7d]) )\r\nor sum by (fish) ( increase(bot_command_total{job=~\"$job\", command=\"cast\", result=\"caught\", location=\"3\"}[7d]) )\r\n",
     "legendFormat": "{{fish}}"
    }
   ]
  },
  {
   "title": "Водохранилище",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum by (fish) (\r\n    increase( fish_caught_total{job=~\"$job\", location=\"Водохранилище\"}[7d] )\r\n  )\r\n  + on (fish)\r\n  sum by (fish) (\r\n    increase( bot_command_total{job=~\"$job\", command=\"cast\", result=\"caught\", location=\"6\"}[7d] )\r\n  )\r\n)\r\nor sum by (fish) ( increase(fish_caught_total{job=~\"$job\", location=\"Водохранилище\"}[7d]) )\r\nor sum by (fish) ( increase(bot_command_total{job=~\"$job\", command=\"cast\", result=\"caught\", location=\"6\"}[7d]) )\r\n",
     "legendFormat": "{{fish}}"
    }
   ]
  },
  {
   "title": "Горная река",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum by (fish) (\r\n    increase( fish_caught_total{job=~\"$job\", location=\"Горная река\"}[7d] )\r\n  )\r\n  + on (fish)\r\n  sum by (fish) (\r\n    increase( bot_command_total{job=~\"$job\", command=\"cast\", result=\"caught\", location=\"5\"}[7d] )\r\n  )\r\n)\r\nor sum by (fish) ( increase(fish_caught_total{job=~\"$job\", location=\"Горная река\"}[7d]) )\r\nor sum by (fish) ( increase(bot_command_total{job=~\"$job\", command=\"cast\", result=\"caught\", location=\"\"}[7d]) )\r\n",
     "legendFormat": "{{fish}}"
    }
   ]
  },
  {
   "title": "Дельта реки",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum by (fish) (\r\n    increase( fish_caught_total{job=~\"$job\", location=\"Дельта реки\"}[7d] )\r\n  )\r\n  + on (fish)\r\n  sum by (fish) (\r\n    increase( bot_command_total{job=~\"$job\", command=\"cast\", result=\"caught\", location=\"7\"}[7d] )\r\n  )\r\n)\r\nor sum by (fish) ( increase(fish_caught_total{job=~\"$job\", location=\"Дельта реки\"}[7d]) )\r\nor sum by (fish) ( increase(bot_command_total{job=~\"$job\", command=\"cast\", result=\"caught\", location=\"7\"}[7d]) )\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Прибрежье моря",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum by (fish) (\r\n    increase( fish_caught_total{job=~\"$job\", location=\"Прибрежье моря\"}[7d] )\r\n  )\r\n  + on (fish)\r\n  sum by (fish) (\r\n    increase( bot_command_total{job=~\"$job\", command=\"cast\", result=\"caught\", location=\"8\"}[7d] )\r\n  )\r\n)\r\nor sum by (fish) ( increase(fish_caught_total{job=~\"$job\", location=\"Прибрежье моря\"}[7d]) )\r\nor sum by (fish) ( increase(bot_command_total{job=~\"$job\", command=\"cast\", result=\"caught\", location=\"8\"}[7d]) )\r\n",
     "legendFormat": "{{fish}}"
    }
   ]
  },
  {
   "title": "Русло Амазонки",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum by (fish) (\r\n    increase( fish_caught_total{job=~\"$job\", location=\"Русло Амазонки\"}[7d] )\r\n  )\r\n  + on (fish)\r\n  sum by (fish) (\r\n    increase( bot_command_total{job=~\"$job\", command=\"cast\", result=\"caught\", location=\"11\"}[7d] )\r\n  )\r\n)\r\nor sum by (fish) ( increase(fish_caught_total{job=~\"$job\", location=\"Русло Амазонки\"}[7d]) )\r\nor sum by (fish) ( increase(bot_command_total{job=~\"$job\", command=\"cast\", result=\"caught\", location=\"11\"}[7d]) )\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Игапо, затопленный лес",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum by (fish) (\r\n    increase( fish_caught_total{job=~\"$job\", location=\"Игапо, затопленный лес\"}[7d] )\r\n  )\r\n  + on (fish)\r\n  sum by (fish) (\r\n    increase( bot_command_total{job=~\"$job\", command=\"cast\", result=\"caught\", location=\"12\"}[7d] )\r\n  )\r\n)\r\nor sum by (fish) ( increase(fish_caught_total{job=~\"$job\", location=\"Игапо, затопленный лес\"}[7d]) )\r\nor sum by (fish) ( increase(bot_command_total{job=~\"$job\", command=\"cast\", result=\"caught\", location=\"12\"}[7d]) )\r\n",
     "legendFormat": "{{fish}}"
    }
   ]
  },
  {
   "title": "Мангровые заросли",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum by (fish) (\r\n    increase( fish_caught_total{job=~\"$job\", location=\"Мангровые заросли\"}[7d] )\r\n  )\r\n  + on (fish)\r\n  sum by (fish) (\r\n    increase( bot_command_total{job=~\"$job\", command=\"cast\", result=\"caught\", location=\"13\"}[7d] )\r\n  )\r\n)\r\nor sum by (fish) ( increase(fish_caught_total{job=~\"$job\", location=\"Мангровые заросли\"}[7d]) )\r\nor sum by (fish) ( increase(bot_command_total{job=~\"$job\", command=\"cast\", result=\"caught\", location=\"13\"}[7d]) )\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Коралловые отмели",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 198 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum by (fish) (\r\n    increase( fish_caught_total{job=~\"$job\", location=\"Коралловые отмели\"}[7d] )\r\n  )\r\n  + on (fish)\r\n  sum by (fish) (\r\n    increase( bot_command_total{job=~\"$job\", command=\"cast\", result=\"caught\", location=\"14\"}[7d] )\r\n  )\r\n)\r\nor sum by (fish) ( increase(fish_caught_total{job=~\"$job\", location=\"Коралловые отмели\"}[7d]) )\r\nor sum by (fish) ( increase(bot_command_total{job=~\"$job\", command=\"cast\", result=\"caught\", location=\"14\"}[7d]) )\r\n",
     "legendFormat": "{{fish}}"
    }
   ]
  },
  {
   "title": "Фьорд",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 207 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum by (fish) (\r\n    increase( fish_caught_total{job=~\"$job\", location=\"Фьорд\"}[7d] )\r\n  )\r\n  + on (fish)\r\n  sum by (fish) (\r\n    increase( bot_command_total{job=~\"$job\", command=\"cast\", result=\"caught\", location=\"9\"}[7d] )\r\n  )\r\n)\r\nor sum by (fish) ( increase(fish_caught_total{job=~\"$job\", location=\"Фьорд\"}[7d]) )\r\nor sum by (fish) ( increase(bot_command_total{job=~\"$job\", command=\"cast\", result=\"caught\", location=\"9\"}[7d]) )\r\n",
     "legendFormat": "{{fish}}"
    }
   ]
  },
  {
   "title": "Открытый океан",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 217 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum by (fish) (\r\n    increase( fish_caught_total{job=~\"$job\", location=\"Открытый океан\"}[7d] )\r\n  )\r\n  + on (fish)\r\n  sum by (fish) (\r\n    increase( bot_command_total{job=~\"$job\", command=\"cast\", result=\"caught\", location=\"10\"}[7d] )\r\n  )\r\n)\r\nor sum by (fish) ( increase(fish_caught_total{job=~\"$job\", location=\"Открытый океан\"}[7d]) )\r\nor sum by (fish) ( increase(bot_command_total{job=~\"$job\", command=\"cast\", result=\"caught\", location=\"10\"}[7d]) )\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}